# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

class ResponsePacketContents(object):
    NONE = 0
    StatusResponse = 1
    ConfigurationResponse = 2
    DataResponse = 3
